// <auto-generated />
using System;
using Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430120404_create database")]
    partial class createdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Models.Attendee", b =>
                {
                    b.Property<Guid>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AttendingEventIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendeeId");

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            AttendeeId = new Guid("780e20f8-3393-4e7e-94c7-4ff714dada37"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "sunniva.pedersen@origin.no",
                            Name = "Sunniva Pedersen",
                            Title = "LEAD"
                        },
                        new
                        {
                            AttendeeId = new Guid("7e8024a5-4b73-4b77-a27e-c66b9b041277"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "oliver.bakken@origin.no",
                            Name = "Oliver Bakken",
                            Title = "LEAD"
                        },
                        new
                        {
                            AttendeeId = new Guid("6735a525-7ed5-4ed1-829b-5e33c3124ce1"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "frida.vedvik@origin.no",
                            Name = "Frida Vedvik",
                            Title = "LEAD"
                        },
                        new
                        {
                            AttendeeId = new Guid("6684a409-71be-4415-b221-ebee0667b6e0"),
                            AttendingEventIds = "[]",
                            Department = "MICROSOFT",
                            Email = "camilla.fjeld@origin.no",
                            Name = "Camilla Fjeld",
                            Title = "SENIOR"
                        },
                        new
                        {
                            AttendeeId = new Guid("56a1bbb0-a096-4fba-ad1b-245d63daac37"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "leah.eide@origin.no",
                            Name = "Leah Eide",
                            Title = "EXECUTIVE"
                        },
                        new
                        {
                            AttendeeId = new Guid("cb88041e-a34e-4c0f-b375-66e60287261b"),
                            AttendingEventIds = "[]",
                            Department = "UX",
                            Email = "marte.kristensen@origin.no",
                            Name = "Marte Kristensen",
                            Title = "LEAD"
                        },
                        new
                        {
                            AttendeeId = new Guid("8b354640-6247-442c-84e5-d4779f89f322"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "jonas.edvardsen@origin.no",
                            Name = "Jonas Edvardsen",
                            Title = "JUNIOR"
                        },
                        new
                        {
                            AttendeeId = new Guid("f58825e5-6765-47f7-beb7-d8183313945a"),
                            AttendingEventIds = "[]",
                            Department = "MICROSOFT",
                            Email = "noah.kvarme@origin.no",
                            Name = "Noah Kvarme",
                            Title = "JUNIOR"
                        },
                        new
                        {
                            AttendeeId = new Guid("5b984b52-821b-486d-9fdc-0000710225b7"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "marte.smedsrud@origin.no",
                            Name = "Marte Smedsrud",
                            Title = "EXECUTIVE"
                        },
                        new
                        {
                            AttendeeId = new Guid("eb913095-b15e-405e-b638-3b5f78f2e980"),
                            AttendingEventIds = "[]",
                            Department = "JAVA",
                            Email = "sindre.nygaard@origin.no",
                            Name = "Sindre Nygård",
                            Title = "JUNIOR"
                        });
                });

            modelBuilder.Entity("Demo.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AttendeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodAlternatives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpenSpots")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("SkillDayId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("37659ba4-0f4a-4fb5-a76d-588bfdee1986"),
                            Address = "Gamle Damvollen 6, Stavanger",
                            Date = new DateTime(2024, 2, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Discover the joy of SkillDay Terrengsykling",
                            FoodAlternatives = "Cobbler;Ricotta Stuffed Ravioli",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Terrengsykling",
                            OpenSpots = 1,
                            SkillDayId = new Guid("c63904d9-5129-4418-a07b-ae3d59fc3705")
                        },
                        new
                        {
                            EventId = new Guid("07840b21-8b2e-49b2-99f1-4e1bc65b58ad"),
                            Address = "Kirkebråten 7, Stavanger",
                            Date = new DateTime(2024, 2, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join in on a session of SkillDay Terrengsykling",
                            FoodAlternatives = "Sundae;Pasta with Tomato and Basil",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Terrengsykling",
                            OpenSpots = 1,
                            SkillDayId = new Guid("c63904d9-5129-4418-a07b-ae3d59fc3705")
                        },
                        new
                        {
                            EventId = new Guid("6d62483b-aa5c-461f-bf1a-2d5e5e3c489d"),
                            Address = "Kuvika 49, Stavanger",
                            Date = new DateTime(2024, 2, 24, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience the rush of SkillDay Rytter",
                            FoodAlternatives = "Cheesecake;Chicken Fajitas",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Rytter",
                            OpenSpots = 0,
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49")
                        },
                        new
                        {
                            EventId = new Guid("f3a3314e-a4fc-4fcc-97e9-b7c35330f04c"),
                            Address = "Øvre Geiteryggløkka 8, Stavanger",
                            Date = new DateTime(2023, 11, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Challenge yourself to learn SkillDay Rytter",
                            FoodAlternatives = "Frozen Yogurt;Pierogi",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Rytter",
                            OpenSpots = 7,
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49")
                        },
                        new
                        {
                            EventId = new Guid("73469058-13b5-480a-afc5-1bd657bb1ff5"),
                            Address = "Oskars Gate 74, Stavanger",
                            Date = new DateTime(2023, 11, 28, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn how to master SkillDay Rytter",
                            FoodAlternatives = "Upside Down Pineapple Cake;Caesar Salad",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Rytter",
                            OpenSpots = 9,
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49")
                        },
                        new
                        {
                            EventId = new Guid("d18a568e-4529-49e9-8333-6a1dcdb493ee"),
                            Address = "Kuhagen 9, Sola",
                            Date = new DateTime(2023, 11, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get better at SkillDay Rytter",
                            FoodAlternatives = "Upside Down Pineapple Cake;Pork Sausage Roll",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Rytter",
                            OpenSpots = 5,
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49")
                        },
                        new
                        {
                            EventId = new Guid("59b81267-907e-45d0-9ed1-637637b54cab"),
                            Address = "Gamle Korsgjerdet 0, Sola",
                            Date = new DateTime(2023, 12, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get better at SkillDay Rytter",
                            FoodAlternatives = "Pie;Poke",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Rytter",
                            OpenSpots = 3,
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49")
                        },
                        new
                        {
                            EventId = new Guid("d6943a80-5c39-4583-92b5-16627957fef3"),
                            Address = "Vestre Elvegjerdet 8, Sola",
                            Date = new DateTime(2024, 1, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Let's try SkillDay Maratonsvømming",
                            FoodAlternatives = "Cupcake;Poutine",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Maratonsvømming",
                            OpenSpots = 6,
                            SkillDayId = new Guid("d7b259a9-a713-4d3e-ab99-5a7962d8655f")
                        },
                        new
                        {
                            EventId = new Guid("056d1854-79dd-4c58-8bb3-61fb69a3af3f"),
                            Address = "Vestre Vassstien 32, Tjelta",
                            Date = new DateTime(2023, 11, 24, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience the rush of SkillDay Taekwondo",
                            FoodAlternatives = "Frozen Yogurt;Chicken Wings",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Taekwondo",
                            OpenSpots = 1,
                            SkillDayId = new Guid("addc06d6-0b37-4a88-b861-0582d9e62d00")
                        },
                        new
                        {
                            EventId = new Guid("ed574cd0-8607-41c2-9f06-eadda5ab6e48"),
                            Address = "Camillasgate 1, Tjelta",
                            Date = new DateTime(2023, 12, 3, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore ways to enjoy SkillDay Taekwondo",
                            FoodAlternatives = "Ice Cream;California Maki",
                            ImageUrl = "https://source.unsplash.com/featured/?SkillDay%20Taekwondo",
                            OpenSpots = 6,
                            SkillDayId = new Guid("addc06d6-0b37-4a88-b861-0582d9e62d00")
                        });
                });

            modelBuilder.Entity("Demo.Models.SkillDay", b =>
                {
                    b.Property<Guid>("SkillDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SkillDayId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("SkillDays");

                    b.HasData(
                        new
                        {
                            SkillDayId = new Guid("c63904d9-5129-4418-a07b-ae3d59fc3705"),
                            Department = "JAVA",
                            Name = "SkillDay: Terrengsykling",
                            ResponsibleId = new Guid("780e20f8-3393-4e7e-94c7-4ff714dada37")
                        },
                        new
                        {
                            SkillDayId = new Guid("b7b5fc68-8267-40de-a007-d883dc112a03"),
                            Department = "JAVA",
                            Name = "SkillDay: Bordtennis",
                            ResponsibleId = new Guid("7e8024a5-4b73-4b77-a27e-c66b9b041277")
                        },
                        new
                        {
                            SkillDayId = new Guid("425213fe-8d55-4fc6-9aa8-3df7a2f78f49"),
                            Department = "JAVA",
                            Name = "SkillDay: Rytter",
                            ResponsibleId = new Guid("6735a525-7ed5-4ed1-829b-5e33c3124ce1")
                        },
                        new
                        {
                            SkillDayId = new Guid("d7b259a9-a713-4d3e-ab99-5a7962d8655f"),
                            Department = "MICROSOFT",
                            Name = "SkillDay: Maratonsvømming",
                            ResponsibleId = new Guid("6684a409-71be-4415-b221-ebee0667b6e0")
                        },
                        new
                        {
                            SkillDayId = new Guid("addc06d6-0b37-4a88-b861-0582d9e62d00"),
                            Department = "JAVA",
                            Name = "SkillDay: Taekwondo",
                            ResponsibleId = new Guid("56a1bbb0-a096-4fba-ad1b-245d63daac37")
                        },
                        new
                        {
                            SkillDayId = new Guid("c4541f82-d18f-44cd-9c4b-8fcaa274785a"),
                            Department = "UX",
                            Name = "SkillDay: Fekting",
                            ResponsibleId = new Guid("cb88041e-a34e-4c0f-b375-66e60287261b")
                        },
                        new
                        {
                            SkillDayId = new Guid("4504080d-6532-4888-a08d-5f0b0f68112a"),
                            Department = "JAVA",
                            Name = "SkillDay: Sportsklatring",
                            ResponsibleId = new Guid("8b354640-6247-442c-84e5-d4779f89f322")
                        },
                        new
                        {
                            SkillDayId = new Guid("5b42228f-3a54-4651-b417-c4287dba47ca"),
                            Department = "MICROSOFT",
                            Name = "SkillDay: Rugby",
                            ResponsibleId = new Guid("f58825e5-6765-47f7-beb7-d8183313945a")
                        },
                        new
                        {
                            SkillDayId = new Guid("fa175f37-a78e-450e-8173-75c7f9203999"),
                            Department = "JAVA",
                            Name = "SkillDay: Softball",
                            ResponsibleId = new Guid("5b984b52-821b-486d-9fdc-0000710225b7")
                        },
                        new
                        {
                            SkillDayId = new Guid("08745bf6-1a56-44ac-9886-5e4d2641e92f"),
                            Department = "JAVA",
                            Name = "SkillDay: BMX racing",
                            ResponsibleId = new Guid("eb913095-b15e-405e-b638-3b5f78f2e980")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Demo.Models.Event", b =>
                {
                    b.HasOne("Demo.Models.Attendee", null)
                        .WithMany("AttendingEvents")
                        .HasForeignKey("AttendeeId");

                    b.HasOne("Demo.Models.SkillDay", "SkillDay")
                        .WithMany("Events")
                        .HasForeignKey("SkillDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillDay");
                });

            modelBuilder.Entity("Demo.Models.SkillDay", b =>
                {
                    b.HasOne("Demo.Models.Attendee", "Responsible")
                        .WithMany("Skilldays")
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo.Models.Attendee", b =>
                {
                    b.Navigation("AttendingEvents");

                    b.Navigation("Skilldays");
                });

            modelBuilder.Entity("Demo.Models.SkillDay", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
